# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a714d75f-3ce7-4894-9fb7-29f4c93f9f72";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a714d75f-3ce7-4894-9fb7-29f4c93f9f72".device = "/dev/disk/by-uuid/a714d75f-3ce7-4894-9fb7-29f4c93f9f72";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8497-F7E9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c13e9b1b-dd46-4a7b-9fc0-42586d576c21"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
